Stages:
  - Name: Source
    Actions:
      - Name: SourceAction
        ActionTypeId:
          Category: Source
          Owner: ThirdParty
          Version: 1
          Provider: GitHub
        Configuration:
          Owner: owner
          Repo: repo
          Branch: branch
          OAuthToken: 'my-github-token'
        OutputArtifacts:
          - Name: SourceOutput
  - Name: Build
    Actions:
      - Name: BuildAction
        ActionTypeId:
          Category: Build
          Owner: AWS
          Version: 1
          Provider: CodeBuild
        Configuration:
          ProjectName: 'MyCodeBuildProject'
        InputArtifacts:
          - Name: SourceOutput
        OutputArtifacts:
          - Name: BuildOutput
  - Name: Deploy
    Actions:
      - Name: DeployAction
        ActionTypeId:
          Category: Deploy
          Owner: AWS
          Version: 1
          Provider: CodeDeploy
        Configuration:
          ApplicationName: 'MyCodeDeployApp'
          DeploymentGroupName: 'MyDeploymentGroup'
        InputArtifacts:
          - Name: BuildOutput
